spring:
  application:
    name: user-service
  profiles:
    active: @activatedProperties@
  config:
    import: configserver:@configurationserver@
  cloud:
    stream:
      function:
        definition: recevoirsessionenvoicart
      bindings:
        recevoirsessionenvoicart-in-0:
          destination: messages.user
          binder: rabbit
          group: user
        recevoirsessionenvoicart-out-0:
          destination: messages.reservation
          binder: rabbit
          group: reservation
