version: "3.9"

networks:
  back-end:
    driver: bridge
  dbfilm:
    driver: bridge
  dbuser:
    driver: bridge
  dbcinema:
    driver: bridge
  dbprogrammation:
    driver: bridge
  dbreservation:
    driver: bridge
services:
  apigateway:
    container_name: "gestioncinema_apigateway"
    build: ./apigateway
    restart: always
    ports:
      - '8080:8080'
    networks:
      - back-end
    depends_on:
      - consul-server
      - configurationserver
      # - cinema
      # - film
      # - programmation
      # - reservation
      # - user
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  cinema:
    container_name: "gestioncinema_cinema"
    build: ./cinema
    restart: always
    ports:
      - '8181:8181'
    depends_on:
      - consul-server
      - configurationserver
      - dbcinema
    networks:
      - back-end
      - dbcinema
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  film:
    container_name: "gestioncinema_film"
    build: ./film
    restart: always
    ports:
      - '8282:8282'
    depends_on:
      - consul-server
      - configurationserver
      - dbfilm
    networks:
      - back-end
      - dbfilm
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  programmation:
    container_name: "gestioncinema_programmation"
    build: ./programmation
    restart: always
    ports:
      - '8383:8383'
    depends_on:
      - consul-server
      - configurationserver
      - dbprogrammation
    networks:
      - back-end
      - dbprogrammation
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  reservation:
    container_name: "gestioncinema_reservation"
    build: ./reservation
    restart: always
    ports:
      - '8484:8484'
    depends_on:
      - rabbitmq
      - consul-server
      - configurationserver
      - dbreservation
    networks:
      - back-end
      - dbreservation
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  user:
    container_name: "gestioncinema_user"
    build: ./user
    restart: always
    ports:
      - '8585:8585'
    depends_on:
      - dbuser
      - configurationserver
      - rabbitmq
      - consul-server
      - zipkin
    networks:
      - back-end
      - dbuser
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}
  configurationserver:
    container_name: "gestioncinema_configurationserver"
    build: ./configurationserver
    ports:
      - '8888:8888'
    restart: always
    networks:
      - back-end
  rabbitmq:
    container_name: "gestioncinema_rabbitmq"
    image: rabbitmq:3.9-management-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=david
    #   - RABBITMQ_DEFAULT_PASS=pass
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - back-end
  consul-server:
    container_name: "gestioncinema_consul_server"
    image: consul
    ports:
      - "8500:8500"
    networks:
      - back-end
  zipkin:
    container_name: "gestioncinema_zipkin"
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - back-end
  dbcinema:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: gestioncinema_cinema
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    networks:
      - dbcinema
  dbfilm:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: gestioncinema_film
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3309:3306"
    networks:
      - dbfilm
  dbprogrammation:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: gestioncinema_programmation
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3310:3306"
    networks:
      - dbprogrammation
  dbreservation:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: gestioncinema_reservation
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3311:3306"
    networks:
      - dbreservation
  dbuser:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: gestioncinema_user
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3312:3306"
    networks:
      - dbuser
  
  