spring:
  application:
    name: apigateway-service
  profiles:
    active: @activatedProperties@
  config:
    import: configserver:@configurationserver@
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping : true
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://10.26.128.3:4200","http://localhost:4200"]
            allowedCredentials: true
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PATCH
            - PUT        
            allowedHeaders:
            - Content-Type  
            - X-Requested-With 
            - Origin
            - Accept
            - Authorization
            exposedHeaders:
            - Authorization 
      routes:
        - id: to-movie
          uri: lb://film-service
          predicates:
            - Path=/movie/**, /genre/**, /format/**, /person/**, /role/**
            - Method=GET,POST,PATCH,PUT,DELETE
          filters:
            - name: Logger
        - id: to-theater
          uri: lb://cinema-service
          predicates:
            - Path=/theater/**, /feature/**, /room/**
            - Method=GET,POST,PATCH,PUT,DELETE
          filters:
            - name: Logger
        - id: to-user
          uri: lb://user-service
          predicates:
            - Path=/user/**, /cart/**, /login/**
            - Method=GET,POST,PATCH,PUT,DELETE
          filters:
            - name: Logger
        - id: to-session
          uri: lb://programmation-service
          predicates:
            - Path=/session/**
            - Method=GET,POST,PATCH,PUT,DELETE
          filters:
            - name: Logger
        - id: to-reservation
          uri: lb://reservation-service
          predicates:
            - Path=/ticket/**
            - Method=GET,POST,PATCH,PUT,DELETE
          filters:
            - name: Logger
      discovery:
        locator:
          enabled: true