spring:
  application:
    name: programmation-service
  profiles:
    active: @activatedProperties@
  config:
    import: configserver:@configurationserver@
  cloud:
    stream:
      bindings:
        envoisession-out-0:
          destination: messages.user
          binder: rabbit
          group: user